apiVersion: v1
kind: Service
metadata:
  name: springpetclinic
  labels:
    env: dev
    app: spc
spec:
  type: NodePort
  selector:
    env: dev
    app: spc
  ports:
    - port: 8080
      protocol: "TCP"
      targetPort: 8080