---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc-lb
  labels:
    app: spc
    env: dev
spec:
  type: LoadBalancer
  selector:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
