apiVersion: v1
kind: Pod
metadata:
  name: springpetclinic
  labels:
    env: Dev
    app: spc
spec:
  containers:
    - name: web
      image: shaikkhajaibrahim/spcjan2024:1.0
      ports: 
        - containerPort: 8080
          protocol: "TCP"
      resources:
        requests: 
          memory: 56M
          cpu: 250m
        limits:
          memory: 256M
          cpu: 500m